// Bounded: a double that knows how wrong it might be -- the number type of
// the filters.
//
// A Bounded is a double, value, and a bound on its error, error, with one
// promise:
//
//   |value - exact| <= error
//
// where exact is what the same formula would give in exact arithmetic. Inputs
// are exact doubles, error 0. Every operation computes its result in plain
// double, as fast as ever, and alongside it a new bound: the operands' errors,
// carried through the operation, plus the rounding of the operation itself.
// At the end of a formula, if |value| > error, then exact cannot have the
// other sign, or be zero: the sign of value is proven. Otherwise the filter
// says "I don't know", and the predicate asks the exact path.
//
// --- why this kind of filter ---
//
// Shewchuk's predicates use static filters: one error constant per predicate,
// derived by hand in his paper (as are Meyer and Pion's, generated by FPG).
// They are a little faster -- one multiplication instead of a bound per
// operation -- but every new formula needs its derivation redone, and a wrong
// constant gives wrong answers silently. This filter is dynamic: the bound is
// computed with the value, by the same operators, for any formula written as
// a template (see orient2d.h). It costs two or three times a plain double
// evaluation, still tens of times less than an exact one, and it is sound by
// construction -- the argument below holds for every formula at once. A
// static filter can be put in front of it later, for the hottest predicate,
// if a profile asks for one.
//
// --- the rules, and why they are sound ---
//
// Write u = 2^-53, the unit roundoff: rounding to nearest changes a real x by
// at most u|x|. For operands a and b, with exact values within a.error and
// b.error of their values:
//
//   a +- b   the operands' errors add, and the operation rounds once:
//            error = a.error + b.error + u|value|
//
//   a * b    (a + da)(b + db) - ab = a db + b da + da db, with |da| <= a.error
//            and |db| <= b.error, and the operation rounds once:
//            error = |a| b.error + |b| a.error + a.error b.error + u|value|
//
//   -a       exact: the same error.
//
// Two details make the bound safe rather than nearly safe:
//
//   The bound is itself computed in double, and those few operations can each
//   round down, leaving error a hair below the true bound. kInflate covers
//   that: each new error is multiplied by 1 + 2^-48, which absorbs the
//   rounding of about thirty operations, where a product's bound has seven.
//   It also covers using u|value| where the rule needs u|x| for the unrounded
//   x, which can be larger by a factor of (1 + u). Without kInflate no test
//   fails -- a worst-case bound is almost always far above the true error --
//   but the argument above has a gap, so it stays.
//
//   The rounding term u|value| is relative, which is true only while results
//   stay out of the subnormal range, where rounding errors become absolute.
//   That is the same range the exact path needs (kernel/eft.h: products above
//   2^-969), and the domain and seed checks will enforce it for both.
//
// And two cases fail safe on their own: an error that overflows to infinity,
// or a NaN, makes |value| > error false, so the sign is "don't know", and the
// exact path decides. The filter can be unsure; it cannot be wrong.
#pragma once
#include <cmath>
#include <optional>

constexpr double kU = 0x1p-53;             // unit roundoff: half an ulp of 1
constexpr double kInflate = 1.0 + 0x1p-48; // covers the bound's own rounding

// A double and a certified bound on its distance from the exact value.
//
// A plain struct with public members: unlike an Expansion, it has no internal
// invariant that outside code could break -- the promise is between the
// operators below, which are the only things that should make one.
struct Bounded
{
    double value = 0.0; // the double result
    double error = 0.0; // |value - exact| <= error, always

    Bounded() = default; // zero, exact
    explicit Bounded(double v) : value(v)
    {
    } // an input: exact
    Bounded(double v, double e) : value(v), error(e)
    {
    } // for the operators
};

// The four operators, by the rules at the top of this file. Each computes the
// double result as usual, then the bound, then inflates it.
inline Bounded operator+(const Bounded &a, const Bounded &b)
{
    Bounded res;
    res.value = a.value + b.value;
    res.error = a.error + b.error + kU * std::abs(res.value);
    res.error *= kInflate;
    return res;
}

inline Bounded operator-(const Bounded &a, const Bounded &b)
{
    Bounded res;
    res.value = a.value - b.value;
    res.error = a.error + b.error + kU * std::abs(res.value);
    res.error *= kInflate;
    return res;
}

inline Bounded operator-(const Bounded &a)
{
    Bounded res;
    res.value = -a.value;
    res.error = a.error;
    return res;
}

inline Bounded operator*(const Bounded &a, const Bounded &b)
{
    Bounded res;
    res.value = a.value * b.value;
    res.error = std::abs(a.value) * b.error + std::abs(b.value) * a.error +
                a.error * b.error + kU * std::abs(res.value);
    res.error *= kInflate;
    return res;
}

// The sign of the exact value, if the bound proves it; nothing if it cannot.
//
//   |value| > error         the exact value is on value's side of zero: its
//                           sign is value's
//   value == 0, error == 0  the exact value is exactly zero, and was never
//                           rounded: x - x of the same input, or a product
//                           with an exact zero
//   otherwise               zero is within the bound: don't know
//
// std::optional rather than an int, because 0 is a real answer here -- the
// exact value can be certainly zero -- and must not be confused with "don't
// know". A predicate tests it with `if (s)` and reads it with `*s`.
inline std::optional<int> certain_sign(const Bounded &a)
{
    if (std::abs(a.value) > a.error)
    {
        return a.value > 0 ? 1 : -1;
    }
    if (a.value == 0 && a.error == 0)
    {
        return 0;
    }
    return std::nullopt;
}
